# Generated by Django 4.2.21 on 2025-07-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo_url',
        ),
    ]
