# Generated by Django 5.2.1 on 2025-05-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_by', to='professors.module')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to='professors.professor')),
            ],
            options={
                'unique_together': {('prof', 'module', 'semester')},
            },
        ),
    ]
