# Generated by Django 4.2.21 on 2025-06-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaches',
            name='new_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_offered', to='professors.semester'),
        ),
    ]
