# Generated by Django 4.2.21 on 2025-06-22 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_teaches_new_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaches',
            name='semester',
        ),
        migrations.RenameField(
            model_name='teaches',
            old_name='new_semester',
            new_name='semester',
        ),
    ]
