# Generated by Django 5.2.1 on 2025-05-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_teaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
