# Generated by Django 5.2.1 on 2025-05-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_professor_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='website',
            new_name='bio',
        ),
    ]
