# Generated by Django 4.2.21 on 2025-07-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_remove_teaches_new_semester_alter_teaches_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='teaches',
            options={'verbose_name': 'Teaching Record', 'verbose_name_plural': 'Teaching Records'},
        ),
    ]
