# Generated by Django 4.2.21 on 2025-07-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_alter_faculty_options_alter_teaches_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Special Term I'), (4, 'Special Term II')]),
        ),
    ]
