# Generated by Django 5.2.1 on 2025-05-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_rename_website_professor_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='bio',
        ),
    ]
