# Generated by Django 4.2.21 on 2025-06-13 13:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=20000, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 6, 13, 21, 21, 57, 33038))),
                ('rating', models.FloatField(default=0.0)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='professors.module')),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='professors.professor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=20000, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 6, 13, 21, 21, 57, 33038))),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_replies', to=settings.AUTH_USER_MODEL)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.review')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
