# Generated by Django 4.2.21 on 2025-06-16 08:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 16, 46, 22, 854554)),
        ),
        migrations.AlterField(
            model_name='review',
            name='module_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='professors.module'),
        ),
        migrations.AlterField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 16, 46, 22, 854554)),
        ),
    ]
