# Generated by Django 4.2.21 on 2025-06-16 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reply_timestamp_alter_review_module_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='module_id',
            new_name='module_code',
        ),
        migrations.AlterField(
            model_name='reply',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 19, 56, 25, 680255)),
        ),
        migrations.AlterField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 19, 56, 25, 680255)),
        ),
    ]
