# Generated by Django 4.2.21 on 2025-06-19 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_module_id_review_module_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 10, 44, 47, 83675)),
        ),
        migrations.AlterField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 10, 44, 47, 83675)),
        ),
    ]
