# Generated by Django 4.2.21 on 2025-06-21 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_reply_timestamp_alter_review_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
